1. Import the numpy package under the name np (★☆☆)
2. Print the numpy version and the configuration (★☆☆)
3. Create a null vector of size 10 (★☆☆)
4. How to find the memory size of any array (★☆☆)
5. How to get the documentation of the numpy add function from the command line? (★☆☆)
6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
7. Create a vector with values ranging from 10 to 49 (★☆☆)
8. Reverse a vector (first element becomes last) (★☆☆)
9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
11. Create a 3x3 identity matrix (★☆☆)
12. Create a 3x3x3 array with random values (★☆☆)
13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
14. Create a random vector of size 30 and find the mean value (★☆☆)
15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
16. How to add a border (filled with 0's) around an existing array? (★☆☆)
17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
22. Normalize a 5x5 random matrix (★☆☆)
23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
26. What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
28. What are the result of the following expressions? (★☆☆)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
29. How to round away from zero a float array ? (★☆☆)
30. How to find common values between two arrays? (★☆☆)
31. How to ignore all numpy warnings (not recommended)? (★☆☆)
32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)
33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
34. How to get all the dates corresponding to the month of July 2016? (★★☆)
35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
40. Create a random vector of size 10 and sort it (★★☆)
41. How to sum a small array faster than np.sum? (★★☆)
42. Consider two random array A and B, check if they are equal (★★☆)
43. Make an array immutable (read-only) (★★☆)
44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)
47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
49. How to print all the values of an array? (★★☆)
50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [31]:
#Import the numpy package under the name np (★☆☆)
import numpy as np
#Print the numpy version and the configuration (★☆☆)
print(np.__version__)
print(np.__config__.show())
#Create a null vector of size 10 (★☆☆)
null_vector = np.zeros(10)
print(null_vector)
#How to find the memory size of any array (★☆☆)
memory_size = null_vector.size * null_vector.itemsize
print("Memory size of null vector:", memory_size)
#Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
null_vector[4] = 1
print(null_vector)
#Create a vector with values ranging from 10 to 49 (★☆☆)
vector_10_to_49 = np.arange(10, 50)
print(vector_10_to_49)
#Reverse a vector (first element becomes last) (★☆☆)
reversed_vector = vector_10_to_49[::-1]
print(reversed_vector)
#Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
matrix = np.arange(0, 9).reshape(3, 3)
print(matrix)
#Find indices of non-zero elements from [1, 2, 0, 0, 4, 0] (★☆☆)
non_zero_indices = np.nonzero([1, 2, 0, 0, 4, 0])
print(non_zero_indices)
#Create a 3x3 identity matrix (★☆☆)
identity_matrix = np.eye(3)
print(identity_matrix)
#Create a 3x3x3 array with random values (★☆☆)
random_array = np.random.random((3, 3, 3))
print(random_array)
#Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)   
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("Minimum value in 10x10 array:", min_value)
print("Maximum value in 10x10 array:", max_value)
#Create a random vector of size 30 and find the mean value (★☆☆)
random_vector_30 = np.random.random(30)
mean_value = random_vector_30.mean()
print("Mean value of random vector of size 30:", mean_value)
#Create a 2d array with 1 on the border and 0 inside (★☆☆)
bordered_array = np.ones((5, 5))
bordered_array[1:-1, 1:-1] = 0
print("2D array with 1 on the border and 0 inside:\n", bordered_array)
#How to add a border (filled with 0's) around an existing array? (★☆☆)
bordered_array_with_zeros = np.pad(bordered_array, pad_width=1, mode='constant', constant_values=0)
print("2D array with a border of 0's:\n", bordered_array_with_zeros)
#What is the result of the following expression? (★☆☆)
'''0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1'''
print("Results of the expressions:")
print("0 * np.nan:", 0 * np.nan)  # NaN
print("np.nan == np.nan:", np.nan == np.nan)  # False
print("np.inf > np.nan:", np.inf > np.nan)  # False
print("np.nan - np.nan:", np.nan - np.nan)  # NaN
print("np.nan in set([np.nan]):", np.nan in set([np.nan]))  # True
print("0.3 == 3 * 0.1:", 0.3 == 3 * 0.1)  # False

#Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal (★☆☆)
diagonal_matrix = np.diag(np.arange(1, 5), k=-1)
print("5x5 matrix with values 1, 2, 3, 4 just below the diagonal:\n", diagonal_matrix)
#Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print("8x8 matrix with a checkerboard pattern:\n", checkerboard_matrix)
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
shape_array = (6, 7, 8)
index_100 = np.unravel_index(99, shape_array)  # 100th element is at index 99 (0-based index)
print("Index of the 100th element in (6,7,8) shape array:", index_100)
#Create a checkerboard 8x8 matrix using the tile function (★☆☆)
checkerboard_tile = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print("Checkerboard 8x8 matrix using tile function:\n", checkerboard_tile)
# Normalize a 5x5 random matrix (★☆☆)
random_matrix_5x5 = np.random.random((5, 5))
normalized_matrix = (random_matrix_5x5 - random_matrix_5x5.min()) / (random_matrix_5x5.max() - random_matrix_5x5.min())
print("Normalized 5x5 random matrix:\n", normalized_matrix)
#Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
color_dtype = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])
print("Custom dtype for color (RGBA):", color_dtype)
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
matrix_5x3 = np.random.random((5, 3))
matrix_3x2 = np.random.random((3, 2))
product_matrix = np.dot(matrix_5x3, matrix_3x2)
print("Product of 5x3 matrix and 3x2 matrix:\n", product_matrix)
#Given a 1D array, negate all elements which are between 3 and 8, in place (★☆☆)
one_d_array = np.random.randint(0, 10, size=10)
print("Original 1D array:", one_d_array)
one_d_array[(one_d_array > 3) & (one_d_array < 8)] *= -1
print("Negated elements between 3 and 8 in place:", one_d_array)
#What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas
'''
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))'''
print("Output of the script:")
print(sum(range(5), -1))  # Output: 9
print(sum(range(5), -1))  # Output: 9
print(sum(range(5), -1))  # Output: 9
# The numpy import does not change the behavior of the sum function here
# because the built-in sum function is used, not numpy's sum.
# The output remains the same regardless of the import.
#Consider an integer vector Z, which of these expressions are legal? (★☆☆)
'''Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z'''
print("Legal expressions with integer vector Z:")
Z = np.array([1, 2, 3, 4])  # Example integer vector
print("Z**Z:", Z**Z)  # Legal
print("2 << Z >> 2:", 2 << Z >> 2)  # Legal
print("Z <- Z:", Z < -Z)  # Legal, but will return a boolean array
print("1j*Z:", 1j * Z)  # Legal, will return a complex array
print("Z/1/1:", Z / 1 / 1)  # Legal, will return a float array
#print("Z<Z>Z:", Z < Z > Z)  # Illegal, will raise an error
# The expression Z<Z>Z is not valid in Python and will raise a SyntaxError.
# The correct way to check if Z is less than Z and greater than Z would be to use logical operators separately.
#What are the result of the following expressions? (★☆☆)
'''np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)'''
print("Results of the expressions:")
print("np.array(0) / np.array(0):", np.array(0) / np.array(0))  # NaN
print("np.array(0) // np.array(0):", np.array(0) // np.array(0))  # ZeroDivisionError
print("np.array([np.nan]).astype(int).astype(float):", np.array([np.nan]).astype(int).astype(float))  # NaN
# The first expression results in NaN because division by zero is undefined.
# The second expression raises a ZeroDivisionError because integer division by zero is not allowed.
# The third expression converts NaN to int, which results in an error, but if it were allowed, it would still be NaN when converted back to float.
#How to round away from zero a float array ? (★☆☆)
def round_away_from_zero(arr):
    return np.sign(arr) * np.ceil(np.abs(arr))
float_array = np.array([-1.5, 2.3, -3.7, 4.0])
rounded_array = round_away_from_zero(float_array)
print("Rounded away from zero float array:", rounded_array)
#How to find common values between two arrays? (★☆☆)
def find_common_values(arr1, arr2):
    return np.intersect1d(arr1, arr2)
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])
common_values = find_common_values(array1, array2)
print("Common values between the two arrays:", common_values)
#How to ignore all numpy warnings (not recommended)? (★☆☆)
def ignore_numpy_warnings():
    import warnings
    warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)
    warnings.filterwarnings("ignore", category=RuntimeWarning)
#####ignore_numpy_warnings()
#s the following expressions true? (★☆☆)
#np.sqrt(-1) == np.emath.sqrt(-1)
print("Is np.sqrt(-1) == np.emath.sqrt(-1)?", np.sqrt(-1) == np.emath.sqrt(-1))  # False
print("Is np.sqrt(-1) == np.emath.sqrt(-1)?", np.sqrt(-1) is np.emath.sqrt(-1))  # False
# The first expression returns False because np.sqrt(-1) results in NaN, while np.emath.sqrt(-1) returns a complex number.
# The second expression checks if they are the same object, which they are not, so it also returns False.
#How to get the dates of yesterday, today and tomorrow? (★☆☆)
def get_dates():
    today = np.datetime64('today', 'D')
    yesterday = today - np.timedelta64(1, 'D')
    tomorrow = today + np.timedelta64(1, 'D')
    return yesterday, today, tomorrow
yesterday, today, tomorrow = get_dates()
print("Yesterday's date:", yesterday)
print("Today's date:", today)
print("Tomorrow's date:", tomorrow)
#How to get all the dates corresponding to the month of July 2016? (★☆☆)
def get_july_2016_dates():
    july_dates = np.arange(np.datetime64('2016-07-01'), np.datetime64('2016-08-01'))
    return july_dates
july_2016_dates = get_july_2016_dates()
print("All dates in July 2016:", july_2016_dates)
#How to compute ((A+B)*(-A/2)) in place (without copy)? (★☆☆)
def compute_in_place(A, B):
    A += B
    A *= -0.5
    return A
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6], dtype=float)
result = compute_in_place(A, B)
print("Result of ((A+B)*(-A/2)) in place:", result)
#Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
def extract_integer_part(arr):
    return arr.astype(int), np.floor(arr), np.trunc(arr), np.round(arr).astype(int)
random_positive_array = np.random.random(10) * 10  # Random positive numbers
integer_parts = extract_integer_part(random_positive_array)
print("Random positive array:", random_positive_array)
print("Integer parts using different methods:")
for method, integer_part in zip(["astype(int)", "np.floor", "np.trunc", "np.round"], integer_parts):
    print(f"{method}: {integer_part}")
#Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
def create_row_matrix():
    return np.tile(np.arange(5), (5, 1))    
row_matrix = create_row_matrix()
print("5x5 matrix with row values ranging from 0 to 4:\n", row_matrix)
#Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def integer_generator(n):
    for i in range(n):
        yield i
def build_array_from_generator(gen):
    return np.fromiter(gen, dtype=int)
gen = integer_generator(10)
array_from_gen = build_array_from_generator(gen)
print("Array built from integer generator:", array_from_gen)
#Create a vector of size 10 with values ranging from 0 to 1, both included (★★☆)
def create_vector_0_to_1(size):
    return np.linspace(0, 1, size)
vector_0_to_1 = create_vector_0_to_1(10)
print("Vector of size 10 with values ranging from 0 to 1:", vector_0_to_1)
#Create a random vector of size 10 and sort it (★★☆)
def create_and_sort_random_vector(size):
    random_vector = np.random.random(size)
    sorted_vector = np.sort(random_vector)
    return sorted_vector
random_sorted_vector = create_and_sort_random_vector(10)
print("Random vector of size 10 sorted:", random_sorted_vector)
#How to sum a small array faster than np.sum? (★★☆)
def fast_sum(arr):
    return np.add.reduce(arr)
small_array = np.array([1, 2, 3, 4, 5])
fast_sum_result = fast_sum(small_array)
print("Sum of small array using fast method:", fast_sum_result)
#Consider two random array A and B, check if they are equal (★★☆)
def check_arrays_equal(A, B):
    return np.array_equal(A, B)
A = np.random.random(10)
B = np.random.random(10)
are_equal = check_arrays_equal(A, B)
print("Are arrays A and B equal?", are_equal)
#Make an array immutable (read-only) (★★☆)
def make_array_read_only(arr):
    arr.setflags(write=False)
    return arr
immutable_array = np.array([1, 2, 3, 4, 5])
immutable_array = make_array_read_only(immutable_array)
print("Immutable array:", immutable_array)
#Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
def cartesian_to_polar(cartesian_coords):
    x = cartesian_coords[:, 0]
    y = cartesian_coords[:, 1]
    r = np.sqrt(x**2 + y**2)
    theta = np.arctan2(y, x)
    return np.column_stack((r, theta))
cartesian_coords = np.random.random((10, 2)) * 10  # Random 10x2 matrix
polar_coords = cartesian_to_polar(cartesian_coords)
print("Cartesian coordinates:\n", cartesian_coords)
print("Polar coordinates:\n", polar_coords)

#Create random vector of size 10 and replace the maximum value by 0 (★★☆)
def replace_max_with_zero(arr):
    arr[arr.argmax()] = 0
    return arr
random_vector_10 = np.random.random(10)
random_vector_10 = replace_max_with_zero(random_vector_10)
print("Random vector of size 10 with maximum value replaced by 0:", random_vector_10)

#Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★#Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
def create_cauchy_matrix(X, Y):
    X = X[:, np.newaxis]  # Reshape X to a column vector
    Y = Y[np.newaxis, :]  # Reshape Y to a row vector
    return 1.0 / (X - Y)
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
cauchy_matrix = create_cauchy_matrix(X, Y)
print("Cauchy matrix C (Cij = 1/(xi - yj)):\n", cauchy_matrix)

#Print the minimum and maximum representable value for each numpy scalar type (★★☆)
def print_numpy_scalar_limits():
    for dtype in [np.int8, np.int16, np.int32, np.int64, 
                  np.uint8, np.uint16, np.uint32, np.uint64,
                  np.float16, np.float32, np.float64]:
        print(f"Type: {dtype}, Min: {np.iinfo(dtype).min if np.issubdtype(dtype, np.integer) else np.finfo(dtype).min}, Max: {np.iinfo(dtype).max if np.issubdtype(dtype, np.integer) else np.finfo(dtype).max}")
print_numpy_scalar_limits()
#How to print all the values of an array? (★★☆)
def print_all_values(arr):
    np.set_printoptions(threshold=np.inf)  # Set threshold to infinity to print all values
    print(arr)
print_all_values(np.random.random(100))  # Example array with 100 random values
def find_closest_value(arr, scalar):
    idx = (np.abs(arr - scalar)).argmin()  # Find index of closest value
    return arr[idx]
scalar_value = 0.5
random_vector = np.random.random(10)  # Random vector of size 10
closest_value = find_closest_value(random_vector, scalar_value)
print("Random vector:", random_vector)
print("Closest value to", scalar_value, "in the random vector:", closest_value)
def find_closest_value(arr, scalar):
    idx = (np.abs(arr - scalar)).argmin()  # Find index of closest value
    return arr[idx]
scalar_value = 0.5
random_vector = np.random.random(10)  # Random vector of size 10
closest_value = find_closest_value(random_vector, scalar_value)
print("Random vector:", random_vector)
print("Closest value to", scalar_value, "in the random vector:", closest_value)
def find_closest_value(arr, scalar):
    idx = (np.abs(arr - scalar)).argmin()  # Find index of closest value
    return arr[idx]
scalar_value = 0.5
random_vector = np.random.random(10)  # Random vector of size 10
closest_value = find_closest_value(random_vector, scalar_value)
print("Random vector:", random_vector)
print("Closest value to", scalar_value, "in the random vector:", closest_value)
def find_closest_value(arr, scalar):
    idx = (np.abs(arr - scalar)).argmin()  # Find index of closest value
    return arr[idx]
scalar_value = 0.5
random_vector = np.random.random(10)  # Random vector of size 10
closest_value = find_closest_value(random_vector, scalar_value)
print("Random vector:", random_vector)
print("Closest value to", scalar_value, "in the random vector:", closest_value)
#How to find the closest value (to a given scalar) in a vector? (★★☆)
def find_closest_value(arr, scalar):
    idx = (np.abs(arr - scalar)).argmin()  # Find index of closest value
    return arr[idx]
scalar_value = 0.5
random_vector = np.random.random(10)  # Random vector of size 10
closest_value = find_closest_value(random_vector, scalar_value)
print("Random vector:", random_vector)
print("Closest value to", scalar_value, "in the random vector:", closest_value)
#Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
def create_structured_array(positions, colors):
    dtype = np.dtype([('position', 'f4', (2,)), ('color', 'f4', (3,))])
    structured_array = np.zeros(len(positions), dtype=dtype)
    structured_array['position'] = positions
    structured_array['color'] = colors
    return structured_array
positions = np.random.random((5, 2))  # Random positions
colors = np.random.random((5, 3))  # Random colors
structured_array = create_structured_array(positions, colors)
print("Structured array with positions and colors:\n", structured_array)
#Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
def pointwise_distances(coords):
    x = coords[:, 0]
    y = coords[:, 1]
    distances = np.sqrt(x**2 + y**2)  # Euclidean distance from origin
    return distances
random_coords = np.random.random((100, 2))  # Random vector with shape (100, 2)
distances = pointwise_distances(random_coords)
print("Random coordinates:\n", random_coords)
print("Pointwise distances from origin:\n", distances)
#How to convert a float (32 bits) array into an integer (32 bits) in place?
def float_to_int_in_place(arr):
    arr_view = arr.view(np.int32)  # View the float array as an int array
    arr_view[:] = arr.astype(np.int32)  # Convert and assign back
    return arr_view
float_array = np.random.random(10).astype(np.float32)  # Random float array
int_array = float_to_int_in_place(float_array)
print("Float array:", float_array)
print("Converted integer array in place:", int_array)
#How to read the following file? (★★☆)
def read_file(filename):
    data = np.genfromtxt(filename, delimiter=',', names=True, dtype=None, encoding='utf-8')
    return data
filename = 'data.csv'  # Replace with your actual file path
try:
    data = read_file(filename)
    print("Data read from file:\n", data)
except FileNotFoundError:
    print(f"File {filename} not found. Please check the path.")
#What is the equivalent of enumerate for numpy arrays? (★★☆)
def numpy_enumerate(arr):
    return np.ndenumerate(arr)
array_example = np.array([[1, 2, 3], [4, 5, 6]])
enumerated_array = numpy_enumerate(array_example)
for index, value in enumerated_array:
    print(f"Index: {index}, Value: {value}")
#Generate a generic 2D Gaussian-like array (★★☆)
def generate_gaussian_array(shape, mean=0, std=1):
    x = np.linspace(-mean, mean, shape[0])
    y = np.linspace(-mean, mean, shape[1])
    X, Y = np.meshgrid(x, y)
    Z = np.exp(-(X**2 + Y**2) / (2 * std**2))
    return Z
gaussian_array = generate_gaussian_array((5, 5))
print("Generic 2D Gaussian-like array:\n", gaussian_array)
#How to randomly place p elements in a 2D array? (★★☆)
def randomly_place_elements(array, p):
    indices = np.random.choice(array.size, p, replace=False)  # Randomly choose indices
    array.flat[indices] = 1  # Place 1 at the chosen indices
    return array
array_2d = np.zeros((5, 5))  # Create a 5x5 array
p_elements = 5  # Number of elements to place
array_with_elements = randomly_place_elements(array_2d, p_elements)
print("2D array with randomly placed elements:\n", array_with_elements)
#Subtract the mean of each row of a matrix (★★☆)
def subtract_row_mean(matrix):
    row_means = matrix.mean(axis=1, keepdims=True)  # Compute mean of each row
    return matrix - row_means  # Subtract mean from each row
matrix_example = np.random.random((4, 4))  # Random 4x4 matrix
result_matrix = subtract_row_mean(matrix_example)
print("Original matrix:\n", matrix_example)
print("Matrix after subtracting row means:\n", result_matrix)
#How to sort an array by the nth column? (★★☆)
def sort_by_nth_column(array, n):
    return array[array[:, n].argsort()]  # Sort by nth column using argsort
array_to_sort = np.random.random((5, 3))  # Random 5x3 array
n = 1  # Column index to sort by
sorted_array = sort_by_nth_column(array_to_sort, n)
print("Original array:\n", array_to_sort)
print("Array sorted by column", n, ":\n", sorted_array)
#How to tell if a given 2D array has null columns? (★★☆)
def has_null_columns(array):
    return np.any(~array.any(axis=0))  # Check if any column has all zeros
array_2d_example = np.array([[1, 0, 3], [0, 0, 0], [4, 5, 6]])  # Example 2D array
null_columns_exist = has_null_columns(array_2d_example)
print("Does the 2D array have null columns?", null_columns_exist)
#Find the nearest value from a given value in an array (★★☆)
def find_nearest_value(array, value):
    idx = (np.abs(array - value)).argmin()  # Find index of nearest value
    return array[idx]
value_to_find = 0.5
random_array = np.random.random(10)  # Random array of size 10
nearest_value = find_nearest_value(random_array, value_to_find)
print("Random array:", random_array)
print("Nearest value to", value_to_find, "in the random array:", nearest_value)
#Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
def compute_sum_with_iterator(arr1, arr2):
    # Broadcast arr1 and arr2 to a common shape
    arr1_b, arr2_b = np.broadcast_arrays(arr1, arr2)
    out = np.empty(arr1_b.shape)
    it = np.nditer([arr1_b, arr2_b, out], flags=['multi_index', 'refs_ok', 'buffered'],
                   op_flags=[['readonly'], ['readonly'], ['writeonly']])
    for x, y, z in it:
        z[...] = x + y
    return out

# Use the already defined arr1 and arr2 variables
sum_result = compute_sum_with_iterator(arr1, arr2)
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Sum of arrays using iterator:\n", sum_result)
#Create an array class that has a name attribute (★★☆)
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', '')
# Example usage
named_array = NamedArray(np.array([1, 2, 3]), name='MyArray')
print("Named array:", named_array)
# Print the name attribute
print("Array name:", named_array.name)
#Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
def add_to_vector_elements(base_vector, indices, value=1):
    for index in np.unique(indices):  # Use unique indices to avoid repeated additions
        base_vector[index] += value
    return base_vector
base_vector = np.array([0, 0, 0, 0, 0])
indices = np.array([0, 1, 2, 2, 3])  # Indices to add 1 to
result_vector = add_to_vector_elements(base_vector, indices)
print("Base vector:", base_vector)
print("Indices to add 1:", indices)
print("Result vector after adding 1 to indexed elements:", result_vector)
#How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
def accumulate_to_array(X, I, F=None):
    if F is None:
        F = np.zeros(np.max(I) + 1)  # Create an array of zeros with size based on max index
    np.add.at(F, I, X)  # Accumulate elements of X to F at indices I
    return F
X = np.array([1, 2, 3, 4, 5])  # Vector to accumulate
I = np.array([0, 1, 2, 2, 3])  # Indices for accumulation
F = np.array([0, 0, 0, 0, 0])  # Initial array to accumulate into
result_array = accumulate_to_array(X, I, F)
print("Vector X:", X)
print("Index list I:", I)
print("Initial array F:", F)
print("Result array after accumulation:", result_array)
#Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
def count_unique_colors(image):
    unique_colors = np.unique(image.reshape(-1, image.shape[2]), axis=0)  # Reshape and find unique colors
    return unique_colors.shape[0]  # Return the number of unique colors
image_shape = (100, 100, 3)  # Example image shape
image = np.random.randint(0, 256, size=image_shape, dtype=np.ubyte)  # Random image
unique_color_count = count_unique_colors(image)
print("Number of unique colors in the image:", unique_color_count)
#Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
def sum_over_last_two_axes(array):
    return np.sum(array, axis=(-2, -1))  # Sum over the last two axes
array_4d = np.random.random((2, 3, 4, 5))  # Example 4D array
sum_result = sum_over_last_two_axes(array_4d)
print("Original 4D array shape:", array_4d.shape)
print("Sum over the last two axes:\n", sum_result)
#Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)
def compute_means_by_indices(D, S):
    unique_indices = np.unique(S)  # Get unique indices
    means = np.array([D[S == idx].mean() for idx in unique_indices])  # Compute mean for each index
    return means
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])  # Example vector
S = np.array([0, 0, 1, 1, 2, 2, 2, 3, 3])  # Indices for subsets
means_result = compute_means_by_indices(D, S)
print("Vector D:", D)
print("Subset indices S:", S)
print("Means of subsets of D by indices S:", means_result)
#How to get the diagonal of a dot product? (★★★)
def diagonal_of_dot_product(A, B):
    return np.einsum('ij,ji->i', A, B)  # Use einsum to compute the diagonal of the dot product
A = np.random.random((3, 3))  # Example 3x3 matrix A
B = np.random.random((3, 3))  # Example 3x3 matrix B
diagonal_result = diagonal_of_dot_product(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Diagonal of the dot product of A and B:", diagonal_result)
#Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
def interleave_zeros(vector, num_zeros=3):
    result = np.zeros(len(vector) + (len(vector) - 1) * num_zeros, dtype=vector.dtype)
    result[::num_zeros + 1] = vector
    return result
vector = np.array([1, 2, 3, 4, 5])  # Example vector
interleaved_vector = interleave_zeros(vector)
print("Original vector:", vector)
print("New vector with 3 consecutive zeros interleaved between each value:", interleaved_vector)
#Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
def multiply_with_2d_array(array_3d, array_2d):
    return array_3d * array_2d[:, :, np.newaxis]  # Use broadcasting to multiply
array_3d = np.random.random((5, 5, 3))  # Example 3D array
array_2d = np.random.random((5, 5))  # Example 2D array
result_array = multiply_with_2d_array(array_3d, array_2d)
print("3D array shape:", array_3d.shape)
print("2D array shape:", array_2d.shape)
print("Resulting array shape after multiplication:", result_array.shape)
#How to swap two rows of an array? (★★★)
def swap_rows(array, row1, row2):
    array[[row1, row2]] = array[[row2, row1]]  # Swap rows using indexing
    return array
array_to_swap = np.random.random((4, 4))  # Example 4x4 array
row1, row2 = 0, 2  # Rows to swap
swapped_array = swap_rows(array_to_swap, row1, row2)
print("Original array:\n", array_to_swap)
print("Array after swapping rows", row1, "and", row2, ":\n", swapped_array)
#Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)
def unique_line_segments(triplets):
    segments = set()  # Use a set to store unique segments
    for triplet in triplets:
        # Create segments from the triplet vertices
        segments.add(tuple(sorted((triplet[0], triplet[1]))))
        segments.add(tuple(sorted((triplet[1], triplet[2]))))
        segments.add(tuple(sorted((triplet[2], triplet[0]))))
    return np.array(list(segments))  # Convert set to array
triplets = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6],
                     [5, 6, 7], [6, 7, 8], [7, 8, 9], [8, 9, 0], [9, 0, 1]])  # Example triplets
unique_segments = unique_line_segments(triplets)
print("Unique line segments from the triplets:\n", unique_segments)
#Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
def bincount_to_array(C):
    return np.repeat(np.arange(len(C)), C)  # Repeat indices according to counts in C
C = np.array([0, 2, 3, 1])  # Example bincount array
A = bincount_to_array(C)
print("Bincount array C:", C)
print("Array A such that np.bincount(A) == C:", A)
#How to compute averages using a sliding window over an array? (★★★)
def sliding_window_average(array, window_size):
    return np.convolve(array, np.ones(window_size) / window_size, mode='valid')  # Use convolution for sliding window average
array_example = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])  # Example array
window_size = 3  # Size of the sliding window
average_result = sliding_window_average(array_example, window_size)
print("Original array:", array_example)
print("Sliding window average with size", window_size, ":", average_result)
#Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
def build_shifted_2d_array(Z):
    n = len(Z)
    return np.array([Z[i:i+3] for i in range(n-2)])  # Create rows by shifting
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])  # Example one-dimensional array
shifted_2d_array = build_shifted_2d_array(Z)
print("One-dimensional array Z:", Z)
print("Two-dimensional array with shifted rows:\n", shifted_2d_array)
#How to negate a boolean, or to change the sign of a float inplace? (★★★)
def negate_boolean_inplace(arr):
    arr[:] = ~arr  # Negate boolean array in place
    return arr
def change_sign_float_inplace(arr):
    arr[:] = -arr  # Change sign of float array in place
    return arr
bool_array = np.array([True, False, True, False])  # Example boolean array
float_array = np.array([1.0, -2.0, 3.5, -4.5])  # Example float array
negated_bool_array = negate_boolean_inplace(bool_array.copy())
print("Original boolean array:", bool_array)
print("Negated boolean array in place:", negated_bool_array)
changed_float_array = change_sign_float_inplace(float_array.copy())
print("Original float array:", float_array)
print("Changed sign of float array in place:", changed_float_array)
#Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
def distance_to_lines(P0, P1, p):
    distances = []
    for i in range(len(P0)):
        # Calculate the distance from point p to the line defined by P0[i] and P1[i]
        line_vector = P1[i] - P0[i]
        point_vector = p - P0[i]
        line_length = np.linalg.norm(line_vector)
        if line_length == 0:
            # If the line length is zero, return distance to the point
            distance = np.linalg.norm(point_vector)
        else:
            # Project point_vector onto line_vector
            projection_length = np.dot(point_vector, line_vector) / line_length
            projection = (projection_length / line_length) * line_vector
            distance = np.linalg.norm(point_vector - projection)
        distances.append(distance)
    return np.array(distances)
P0 = np.array([[0, 0], [1, 1], [2, 2]])  # Example points for line start
P1 = np.array([[1, 0], [2, 1], [3, 2]])  # Example points for line end
p = np.array([0.5, 0.5])  # Example point to compute distance from
distances = distance_to_lines(P0, P1, p)
print("Points P0:\n", P0)
print("Points P1:\n", P1)
print("Point p:", p)
print("Distances from point p to each line defined by P0 and P1:", distances)
#Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)
def distance_to_lines_multiple_points(P0, P1, P):
    distances = np.zeros((len(P), len(P0)))  # Initialize distance array
    for i in range(len(P0)):
        line_vector = P1[i] - P0[i]  # Vector representing the line
        for j in range(len(P)):
            point_vector = P[j] - P0[i]  # Vector from line start to point
            line_length = np.linalg.norm(line_vector)
            if line_length == 0:
                # If the line length is zero, return distance to the point
                distances[j, i] = np.linalg.norm(point_vector)
            else:
                # Project point_vector onto line_vector
                projection_length = np.dot(point_vector, line_vector) / line_length
                projection = (projection_length / line_length) * line_vector
                distances[j, i] = np.linalg.norm(point_vector - projection)
    return distances
P0 = np.array([[0, 0], [1, 1], [2, 2]])  # Example points for line start
P1 = np.array([[1, 0], [2, 1], [3, 2]])  # Example points for line end
P = np.array([[0.5, 0.5], [1.5, 1.5], [2.5, 2.5]])  # Example set of points to compute distances from
distances = distance_to_lines_multiple_points(P0, P1, P)
print("Points P0:\n", P0)
print("Points P1:\n", P1)
print("Set of points P:\n", P)
print("Distances from each point in P to each line defined by P0 and P1:\n", distances)
#Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)
def extract_centered_subpart(array, center, shape, fill_value=0):
    center_x, center_y = center
    half_height, half_width = shape[0] // 2, shape[1] // 2
    
    # Calculate the start and end indices for the subpart
    start_x = max(center_x - half_height, 0)
    end_x = min(center_x + half_height + 1, array.shape[0])
    start_y = max(center_y - half_width, 0)
    end_y = min(center_y + half_width + 1, array.shape[1])
    
    # Create a subpart with fill value
    subpart = np.full(shape, fill_value)
    
    # Fill the subpart with the values from the original array
    subpart_slice = array[start_x:end_x, start_y:end_y]
    subpart[:subpart_slice.shape[0], :subpart_slice.shape[1]] = subpart_slice
    
    return subpart
array_example = np.random.randint(0, 10, (5, 5))  # Example array
center = (2, 2)  # Center element coordinates
shape = (3, 3)  # Desired shape of the subpart
subpart = extract_centered_subpart(array_example, center, shape, fill_value=-1)
print("Original array:\n", array_example)
print("Centered subpart with shape", shape, "around center", center, ":\n", subpart)
#Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
def generate_sliding_window_array(Z, window_size):
    return np.array([Z[i:i + window_size] for i in range(len(Z) - window_size + 1)])  # Create sliding windows
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])  # Example array
R = generate_sliding_window_array(Z, 4)  # Window size of 4
print("Original array Z:", Z)
print("Generated array R with sliding windows of size 4:\n", R)
#Compute a matrix rank (★★★)
def compute_matrix_rank(matrix):
    return np.linalg.matrix_rank(matrix)  # Use numpy's matrix_rank function
matrix_example = np.random.random((4, 4))  # Example matrix
rank = compute_matrix_rank(matrix_example)
print("Matrix:\n", matrix_example)
import numpy as np
print("Rank of the matrix:", rank)
#How to find the most frequent value in an array?
def most_frequent_value(array):
    values, counts = np.unique(array, return_counts=True)  # Get unique values and their counts
    max_index = np.argmax(counts)  # Find index of the maximum count
    return values[max_index], counts[max_index]  # Return the most frequent value and its count
array_example = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])  # Example array
most_frequent, frequency = most_frequent_value(array_example)
print("Most frequent value in the array:", most_frequent)
print("Frequency of the most frequent value:", frequency)
#Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
def extract_3x3_blocks(matrix):
    blocks = []
    for i in range(matrix.shape[0] - 2):
        for j in range(matrix.shape[1] - 2):
            block = matrix[i:i + 3, j:j + 3]  # Extract 3x3 block
            blocks.append(block)
    return np.array(blocks)  # Return as an array of blocks
matrix_example = np.random.random((10, 10))  # Example 10x10 matrix
blocks = extract_3x3_blocks(matrix_example)
print("Original 10x10 matrix:\n", matrix_example)
print("Extracted 3x3 blocks:\n", blocks)
#Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self._symmetric = getattr(obj, '_symmetric', True)

    def __setitem__(self, key, value):
        # Only set the symmetric element if not already setting it
        if isinstance(key, tuple) and len(key) == 2 and key[0] != key[1]:
            super().__setitem__(key, value)
            super().__setitem__((key[1], key[0]), value)
        else:
            super().__setitem__(key, value)

# Example usage
symmetric_array = SymmetricArray(np.zeros((3, 3)))  # Create a 3x3 symmetric array
symmetric_array[0, 1] = 5  # Set an element
print("Symmetric array after setting element (0, 1) to 5:\n", symmetric_array)
#Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
def sum_of_matrix_products(matrices, vectors):
    result = np.zeros((matrices[0].shape[0], 1))  # Initialize result with shape (n, 1)
    for matrix, vector in zip(matrices, vectors):
        result += np.dot(matrix, vector)  # Accumulate the product of each matrix and vector
    return result
matrices = [np.random.random((3, 3)) for _ in range(5)]  # Example set of 5 matrices
vectors = [np.random.random((3, 1)) for _ in range(5)]  # Example set of 5 vectors
result_sum = sum_of_matrix_products(matrices, vectors)
print("Sum of matrix products result shape:", result_sum.shape)
#Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
def block_sum(array, block_size):
    shape = (array.shape[0] // block_size, array.shape[1] // block_size, block_size, block_size)
    blocks = array.reshape(shape).sum(axis=(-2, -1))  # Sum over the last two axes (block dimensions)
    return blocks
array_example = np.random.random((16, 16))  # Example 16x16 array
block_size = 4  # Block size of 4x4
result_block_sum = block_sum(array_example, block_size)
print("Original 16x16 array:\n", array_example)
print("Block-sum result with block size", block_size, ":\n", result_block_sum)
#How to implement the Game of Life using numpy arrays? (★★★)
def game_of_life(board, steps):
    for _ in range(steps):
        # Count neighbors
        neighbors = sum(np.roll(np.roll(board, i, 0), j, 1) 
                        for i in [-1, 0, 1] for j in [-1, 0, 1] if (i != 0 or j != 0))
        
        # Apply the rules of the Game of Life
        board = (neighbors == 3) | (board & (neighbors == 2))
    return board
# Example usage
initial_board = np.random.randint(0, 2, (5, 5))  # Random initial board
steps = 3  # Number of steps to simulate
final_board = game_of_life(initial_board, steps)
print("Initial board:\n", initial_board)
print("Final board after", steps, "steps:\n", final_board)
#How to get the n largest values of an array (★★★)
def n_largest_values(array, n):
    return np.partition(array, -n)[-n:]  # Get the n largest values using partition
def cartesian_product(*arrays):
    return np.array(np.meshgrid(*arrays)).T.reshape(-1, len(arrays))  # Create cartesian product of input arrays
#Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
arrays = [np.array([1, 2]), np.array([3, 4]), np.array([5, 6])]  # Example input vectors
cartesian_result = cartesian_product(*arrays)
print("Cartesian product of the input arrays:\n", cartesian_result)
import numpy as np
def create_cauchy_matrix(X, Y):
    X = X[:, np.newaxis]  # Reshape X to a column vector    
    Y = Y[np.newaxis, :]  # Reshape Y to a row vector
    return 1 / (X - Y)  # Create the Cauchy matrix using broadcasting
X = np.array([1, 2, 3])  # Example vector X
Y = np.array([4, 5, 6])  # Example vector Y
cauchy_matrix = create_cauchy_matrix(X, Y)
print("Cauchy matrix from vectors X and Y:\n", cauchy_matrix)
#How to create a record array from a regular array? (★★★)
def create_record_array(array):
    dtype = np.dtype([('value', 'f4')])  # Define a structured dtype
    # Ensure the array is 1D before converting to a record array
    array_1d = np.asarray(array).reshape(-1)
    return array_1d.astype(dtype)  # Convert the regular array to a record array
record_array = create_record_array(array_example)
print("Regular array:", array_example)
print("Record array created from the regular array:\n", record_array)
#Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
def power_of_vector(Z, power):
    return Z ** power  # Element-wise power using broadcasting
Z = np.random.random(10)  # Example large vector
power_result = power_of_vector(Z, 3)
print("Original vector Z:", Z)
print("Z to the power of 3 using element-wise operation:\n", power_result)
#Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
def find_rows_containing_elements(A, B):
    # Ensure B is 2D for consistent iteration
    if B.ndim == 1:
        B = B.reshape(1, -1)
    masks = []
    for b in B:
        mask = np.array([all(elem in row for elem in b) for row in A])
        masks.append(mask)
    # Combine masks: rows that satisfy for any row in B
    final_mask = np.any(masks, axis=0)
    return A[final_mask]
A = np.random.randint(0, 10, (8, 3))  # Example array A
B = np.random.randint(0, 10, (2, 2))  # Example array B
matching_rows = find_rows_containing_elements(A, B)
print("Array A:\n", A)
print("Array B:\n", B)
print("Rows of A that contain elements of each row of B regardless of order:\n", matching_rows)
#Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
def extract_unequal_rows(matrix):
    return matrix[~np.all(matrix[:, 0] == matrix, axis=1)]  # Extract rows with unequal values
matrix_example = np.random.randint(0, 5, (10, 3))  # Example 10x3 matrix
#######unequal_rows = extract_unequal_rows(matrix_example)
print("Original 10x3 matrix:\n", matrix_example)
#######print("Rows with unequal values:\n", unequal_rows)
#Convert a vector of ints into a matrix binary representation (★★★)
def int_to_binary_matrix(vector):
    max_bits = int(vector.max()).bit_length()  # Convert to Python int before calling bit_length
    return np.array([[int(bit) for bit in format(int(num), f'0{max_bits}b')] for num in vector])  # Convert each int to binary
vector_example = np.array([1, 2, 3, 4, 5])  # Example vector of ints
binary_matrix = int_to_binary_matrix(vector_example)
print("Original vector of ints:", vector_example)
print("Matrix binary representation of the vector:\n", binary_matrix)
#Given a two dimensional array, how to extract unique rows? (★★★)
def extract_unique_rows(array):
    return np.unique(array, axis=0)  # Use np.unique to extract unique rows
array_example = np.array([[1, 2], [2, 3], [1, 2], [4, 5]])  # Example two-dimensional array
unique_rows = extract_unique_rows(array_example)
print("Original two-dimensional array:\n", array_example)
import numpy as np
print("Unique rows extracted from the array:\n", unique_rows)
#Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
import numpy as np
def einsum_inner(A, B):
    return np.einsum('i,i->', A, B)  # Inner product
def einsum_outer(A, B):
    return np.einsum('i,j->ij', A, B)  # Outer product
def einsum_sum(A):
    return np.einsum('i->', A)  # Sum of elements
def einsum_mul(A, B):
    return np.einsum('i,i->i', A, B)  # Element-wise multiplication
A = np.array([1, 2, 3])  # Example vector A
B = np.array([4, 5, 6])  # Example vector B
inner_result = einsum_inner(A, B)
outer_result = einsum_outer(A, B)
sum_result = einsum_sum(A)
mul_result = einsum_mul(A, B)
print("Inner product using einsum:", inner_result)
print("Outer product using einsum:\n", outer_result)
print("Sum of elements using einsum:", sum_result)
print("Element-wise multiplication using einsum:", mul_result)
#Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
def sample_path(X, Y, num_samples):
    distances = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)  # Calculate distances between consecutive points
    total_distance = np.sum(distances)  # Total path length
    sample_indices = np.linspace(0, total_distance, num_samples)  # Equidistant sample indices
    sampled_points = np.zeros((num_samples, 2))  # Initialize array for sampled points
    
    current_distance = 0.0
    current_index = 0
    
    for i in range(num_samples):
        while current_index < len(distances) and current_distance + distances[current_index] < sample_indices[i]:
            current_distance += distances[current_index]
            current_index += 1
        
        if current_index == 0:
            sampled_points[i] = [X[0], Y[0]]  # First point
        elif current_index >= len(distances):
            sampled_points[i] = [X[-1], Y[-1]]  # Last point
        else:
            ratio = (sample_indices[i] - (current_distance - distances[current_index])) / distances[current_index]
            sampled_points[i] = [X[current_index] * ratio + X[current_index - 1] * (1 - ratio),
                                 Y[current_index] * ratio + Y[current_index - 1] * (1 - ratio)]
    
    return sampled_points
X = np.array([0, 1, 2, 3, 4])  # Example X coordinates
Y = np.array([0, 1, 0, 1, 0])  # Example Y coordinates
num_samples = 10  # Number of equidistant samples
sampled_path = sample_path(X, Y, num_samples)
print("Sampled path points:\n", sampled_path)
#Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
def select_multinomial_rows(X, n):
    # Check if each row contains only integers and sums to n
    return X[np.all(X == X.astype(int), axis=1) & (X.sum(axis=1) == n)]  # Filter rows based on conditions
X = np.array([[1, 2, 3], [2, 2, 2], [3, 1, 0], [4, 0, 0], [0, 0, 0]])  # Example 2D array
n = 6  # Degrees of the multinomial distribution
selected_rows = select_multinomial_rows(X, n)
print("Original 2D array X:\n", X)
print("Rows that can be interpreted as draws from a multinomial distribution with", n, "degrees:\n", selected_rows)
#Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
def bootstrapped_confidence_intervals(X, n_samples=1000, confidence_level=0.95):
    means = []
    n = len(X)
    for _ in range(n_samples):
        sample = np.random.choice(X, size=n, replace=True)  # Resample with replacement
        means.append(np.mean(sample))  # Compute mean of the sample
    lower_bound = np.percentile(means, (1 - confidence_level) / 2 * 100)  # Lower percentile
    upper_bound = np.percentile(means, (1 + confidence_level) / 2 * 100)  # Upper percentile
    return lower_bound, upper_bound
X = np.random.random(100)  # Example 1D array
confidence_intervals = bootstrapped_confidence_intervals(X)
print("Bootstrapped 95% confidence intervals for the mean of X:", confidence_intervals)

    

2.2.1
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-wgaip4tz/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

C:\Users\user\AppData\Local\Temp\ipykernel_11904\434965482.py:132: RuntimeWarning: invalid value encountered in divide
  print("np.array(0) / np.array(0):", np.array(0) / np.array(0))  # NaN
C:\Users\user\AppData\Local\Temp\ipykernel_11904\434965482.py:133: RuntimeWarning: divide by zero encountered in floor_divide
  print("np.array(0) // np.array(0):", np.array(0) // np.array(0))  # ZeroDivisionError
C:\Users\user\AppData\Local\Temp\ipykernel_11904\434965482.py:134: RuntimeWarning: invalid value encountered in cast
  print("np.array([np.nan]).astype(int).astype(float):", np.array([np.nan]).astype(int).astype(float))  # NaN
C:\Users\user\AppData\Local\Temp\ipykernel_11904\434965482.py:159: RuntimeWarning: invalid value encountered in sqrt
  print("Is np.sqrt(-1) == np.emath.sqrt(-1)?", np.sqrt(-1) == np.emath.sqrt(-1))  # False
C:\Users\user\AppData\Local\Temp\ipykernel_11904\434965482.py:160: RuntimeWarning: invalid value encountered in sqrt
  print("Is np.sqrt(-1) == np.emath.sqrt(-1

File data.csv not found. Please check the path.
Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6
Generic 2D Gaussian-like array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2D array with randomly placed elements:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0.]]
Original matrix:
 [[0.21515823 0.27776453 0.42618877 0.537006  ]
 [0.01466297 0.62239234 0.30741904 0.56472573]
 [0.25748655 0.93308453 0.45589193 0.23234889]
 [0.32667343 0.02638738 0.84521827 0.43457879]]
Matrix after subtracting row means:
 [[-0.14887115 -0.08626486  0.06215939  0.17297662]
 [-0.36263705  0.24509232 -0.06988098  0.18742571]
 [-0.21221642  0.46338155 -0.01381105 -0.23735408]
 [-0.08154104 -0.38182709  0.4370038   0.02636432]]
Original array:
 [[0.17913056 0.21845402 0.74886818]
 [0.62134714 0.18392942 0.43124112]
 [0.00466506 0